---
title: "Figure 2. Jurkat/293t/50_50"
author: "Martin Loza"
---

This is the main workflow to reproduce the Jurkat/293t cells correction shown in Figure 2.

```{r setup}
library(here)
library(patchwork)
library(Canek)
library(Seurat)
library(ggplot2)
library(RNAseqAnalysis)
options(future.globals.maxSize = 4e10)


seed = 777
dimPCA <- 10
ks <- c(1,1,2)
per <- c(0.05, 0.15, 0.3)

dataFile <- here("Data/Results/Jurkat_293t/Raw.Rds")
resultsFile <- here("Data/Results/Figure2")
mytheme <- theme_classic() + theme(text = element_text(size = 20)) 
theme_set(mytheme)
```

# Load data

```{r}
xl <- readRDS(dataFile)
xl
```

## Sampling data. For tests

```{r}
set.seed(seed)
xl <- lapply(xl, RNAseqAnalysis::SampleData, frac = 0.1, seed = seed)
xl
```

# Data preprocessing

```{r}
set.seed(seed)
xl <- lapply(xl, RNAseqAnalysis::SeuratPreprocessing)
```

## Corrections

```{r}
source(here("Results/CorrectData.R"), knitr::knit_global())
```

We create a list with the correction results to ease downstream analyses.

```{r}
datal <- list(Uncorrected = Uncorrected,
              Canek = Canek,
              MNN = MNN,
              Seurat = Seurat,
              scMerge = scMerge, 
              ComBat = ComBat, 
              Liger = Liger, 
              Harmony = Harmony, 
              Scanorama = Scanorama, 
              ComBatseq = ComBatseq)
```

## Save corrections

```{r}
saveRDS(object = datal, file = paste0(resultsFile, "/datal.Rds"))
```

# Metrics

```{r}
# Set up the data frames for metrics results. 
scoresKbet <- data.frame(matrix(integer(), nrow = 1, ncol = length(datal)))
colnames(scoresKbet) <- names(datal)

scoresSilhouette <- data.frame(matrix(integer(), nrow = 1, ncol = length(datal)))
colnames(scoresSilhouette) <- names(datal)
```

## kBET

```{r}
batch = "batch"

for(method in names(datal)){
  if(method == "Liger"){
    reduction <- "Liger"
    dims = ncol(datal$Liger[[reduction]])
  }else if(method == "Harmony"){
    reduction <- "harmony"
    dims = ncol(datal$Harmony[[reduction]])
  }else{
    reduction <- "pca"
    dims <- dimPCA
  }
  
  set.seed(seed)
  scoresKbet[method] <- RNAseqAnalysis::RunKBET(object = datal[[method]], batch = batch, reduction = reduction, dims = dims, per = per, acceptance = TRUE)
}
```

## Silhouette

```{r}
batch = "celltype"

for(method in names(datal)){
  if(method == "Liger"){
    reduction <- "Liger"
    dims = ncol(datal$Liger[[reduction]])
  }else if(method == "Harmony"){
    reduction <- "harmony"
    dims = ncol(datal$Harmony[[reduction]])
  }else{
    reduction <- "pca"
    dims <- dimPCA
  }
  
  set.seed(seed)
  scoresSilhouette[method] <- RNAseqAnalysis::RunSilhouette(object = datal[[method]], batch = batch, reduction = reduction, dims = dims)
}
```

## Save scores

```{r}
saveRDS(object = list(scoresKbet = scoresKbet, scoresSilhouette = scoresSilhouette), file = paste0(resultsFile, "/scores.RDS"))
```