---
title: "Figure 2 plots"
author: "Martin Loza"
---

This is the main workflow to reproduce the Jurkat/293t cells correction plots in Figure 2.

```{r setup}
library(here)
library(patchwork)
library(Seurat)
library(ggplot2)
library(ggrepel)
options(future.globals.maxSize = 4e10)

maxColor = "purple"
resultsFile <- here("Data/Results/Figure2")
plotsFile <- here("Figures/Figure2")
mytheme <- theme_classic() + theme(text = element_text(size = 20)) 
theme_set(mytheme)

## Functions
## Scale the gradient color of gene expression levels plots.
scaleGradient <- function(p, name = "p"){
  x <- (p[[1]] +
          scale_color_gradient(low = "gray", high = maxColor, limits = (c(0,maxExp))) +
          ggtitle(label = "", subtitle = "XIST") + mytheme) +
       (p[[2]] +
          scale_color_gradient(low = "gray", high = maxColor, limits = (c(0,maxExp))) + 
          ggtitle(label = "", subtitle = "CD3D") + mytheme) + plot_layout(nrow = 1, guides = "collect") 
  
  return(x)
}

# Plot pca and umap corrections and gene expression of XIST and CD3D genes.
plotCorrection <- function(object, title = "correction", reduction1 = "pca", reduction2 = "umap"){
  p1 <- DimPlot(object, reduction = reduction1, group.by = "batch") + 
    ggtitle(title) + mytheme
  p2 <- DimPlot(object, reduction = reduction2, group.by = "batch") + 
    mytheme + theme(plot.title = element_blank())
  
  pa <- p1 + p2 + ggtitle(title) + plot_layout(guides = "collect", nrow = 1)
  
  pFea <- FeaturePlot(object, features = c("XIST","CD3D"), 
                      order = TRUE, combine = FALSE, reduction = reduction1)
   
  pb <- scaleGradient(pFea,name = title) + mytheme
  
  return(list(p1 = pa, p2 = pb))
}

# Plot pca corrections and gene expression of XIST and CD3D genes.
plotCorrectionV2 <- function(object, title = "correction", reduction = "pca"){
  pa <- DimPlot(object, reduction = reduction, group.by = "batch") + 
    ggtitle(title) + mytheme + ggtitle(title) 
  
  pFea <- FeaturePlot(object, features = c("XIST","CD3D"), 
                      order = TRUE, combine = FALSE, reduction = reduction)
   
  pb <- scaleGradient(pFea,name = title) + mytheme
  
  return(list(p1 = pa, p2 = pb))
}
```

# Load data

```{r}
datal <- readRDS(file = paste0(resultsFile, "/datal.Rds"))
scores <- readRDS(file = paste0(resultsFile, "/scores.RDS"))
scoresKbet <- scores$scoresKbet
scoresSilhouette <- scores$scoresSilhouette
```

## Setup assay

We want to plot CD3D and XIST gene expressions, but they were not selected as variable features during integrations. Then, we add the original assay to the corrections.

```{r}
RNA <- Seurat::Assays(datal[["Seurat"]], slot = "RNA")
methods <- names(datal)
datal <- lapply(methods, function(m){
  object <- datal[[m
                   ]]
  if(m == "Uncorrected")
    object[["RNA2"]] <- RNA
  else
    object[["RNA"]] <- RNA
  
  return(object)
})
names(datal) <- methods

# Set max value for colour pallete
maxExp = max(GetAssayData(datal[["Uncorrected"]], assay = "RNA2", slot = "data")[c("CD3D","XIST"),])
```

## Metrics plot

```{r}
df <- data.frame("Silhouette" = t(scoresSilhouette), "kBET" = t(scoresKbet), Method = colnames(scoresKbet))

nudge_y <- max(scoresKbet)/10
nudge_x <- max(scoresSilhouette)/10
pMetrics <- ggplot(df, aes(Silhouette, kBET, color = Method, label = Method)) + 
  geom_point(size = 8, alpha = 0.5) +
  geom_text_repel(size = 9, alpha = 1.0, direction = "both", nudge_y = nudge_y, nudge_x = nudge_x) + 
  NoLegend() + ylab("kBET\n(acceptance rate)") + ggtitle("")

pMetrics
```

## Corrections plots

```{r fig.height=25, fig.width=15}
methods <- c("Uncorrected", "Canek", "MNN", "Seurat", "ComBat")
plots <- lapply(methods, function(m){
  if(m == "Liger"){
    reduction = "Liger"
  }else if(m == "Harmony"){
    reduction = "harmony"
  }else{
    reduction = "pca"
  }
  
  return(plotCorrectionV2(object = datal[[m]], title = m, reduction = reduction))
})
names(plots) <- methods
```

## BioRxiv v2 Figure 2. 

```{r fig.height=25, fig.width=15}
layout <- "
aabbbbbb
ccdddddd
eeffffff
gghhhhhh
iijjjjjj
#kkkkkk#
"

pv2 <- wrap_plots(a = plots[[1]]$p1, b = plots[[1]]$p2,
                c = plots[[2]]$p1, d = plots[[2]]$p2,
                e = plots[[3]]$p1, f = plots[[3]]$p2, 
                g = plots[[4]]$p1, h = plots[[4]]$p2,
                i = plots[[5]]$p1, j = plots[[5]]$p2,
                k = pMetrics,
                design = layout)

pv2

# ggsave(pv2, device = "pdf",filename = "Figure2.pdf", path = paste0(plotsFile,"/"), width = 15, height = 25)
ggsave(pv2, device = "png",filename = "Figure2.png", path = paste0(plotsFile,"/"), width = 12, height = 22)
```

## BioRxiv v1 Figure 2.

```{r fig.height=50, fig.width=20}
methods <- names(datal)
plots <- lapply(methods, function(m){
  if(m == "Liger"){
    reduction1 = "Liger"
  }else if(m == "Harmony"){
    reduction1 = "harmony"
  }else{
    reduction1 = "pca"
  }
  
  return(plotCorrection(object = datal[[m]], title = m, reduction1 = reduction1))
})
names(plots) <- names(datal)

layout <- "
ab
cd
ef
gh
ij
kl
mn
op
qr
st
"

pv1 <- wrap_plots(a = plots[[1]]$p1, b = plots[[1]]$p2,
                c = plots[[2]]$p1, d = plots[[2]]$p2,
                e = plots[[3]]$p1, f = plots[[3]]$p2, 
                g = plots[[4]]$p1, h = plots[[4]]$p2,
                i = plots[[5]]$p1, j = plots[[5]]$p2,
                k = plots[[6]]$p1, l = plots[[6]]$p2,
                m = plots[[7]]$p1, n = plots[[7]]$p2,
                o = plots[[8]]$p1, p = plots[[8]]$p2,
                q = plots[[9]]$p1, r = plots[[9]]$p2,
                s = plots[[10]]$p1, t = plots[[10]]$p2,
                design = layout)
pv1
```